on:
    push:
      branches:
        - develop
  
env:
    ACTIVE_API_URL: "<ACTIVE_API_URL>"
    ACTIVE_REGISTRY_URL: "<ACTIVE_REGISTRY_URL>"
    ACTIVE_BACKEND_URI: "<ACTIVE_BACKEND_URI>"
jobs:
    scan:
      runs-on: ubuntu-latest
  
      steps:
  
        - name: Docker login
          uses: docker/login-action@v1
          with:
            registry: ${{ vars.ACTIVE_REGISTRY_URL }}
            username: ${{ vars.ACTIVE_REGISTRY_USER }}
            password: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}

        - name: Install tree utility
          run: sudo apt-get update && sudo apt-get install -y tree
    
        - name: Show Recursive Directory Tree
          run: |
            echo "Current Directory Tree:"
            tree -a -L 3

        - name: Checkout code
         uses: actions/checkout@v3

        - name: Active Testing Scan
          run: >
            docker run
            --add-host=host.docker.internal:host-gateway
            -e ACTIVE_CONFIG_FILE_PATH=/noname/active-config.json
            -e ACTIVE_BACKEND_URI=${{ vars.ACTIVE_BACKEND_URI }}
            -v /home/runner/work/crAPI-at-cicd/crAPI-at-cicd/noname:/noname
            ${{ vars.ACTIVE_REGISTRY_URL }}/active-cli:2.30.0 scan
            --api-url=${{ vars.ACTIVE_API_URL }}
            --api-token=${{ secrets.ACTIVE_API_TOKEN }}
            --test-group-id=${{ vars.TEST_GROUP_ID }}
            --branch-name=${{ github.head_ref || github.ref_name }}
            --severity-threshold=none
            --analyze
  
    deploy:
      needs: scan
      runs-on: ubuntu-latest
      steps:
        - name: echo
          run: echo Security scan passed, deploying to production